### PR TITLE
Allow passing without any tests

### PR DESCRIPTION
**Pull request by chennisden**
**What does this PR do?**

Allows frontend tests to pass. Issue before was that there were no tests found

**What issues does this PR fix or reference?**

#47

### CODE REVIEW

**Comment by codekansas** [comment]
this probably isn't what we want - we want frontend tests, it's just that they fail for some reason

**Comment by chennisden** [comment]
> this probably isn't what we want - we want frontend tests, it's just that they fail for some reason

they dont pass because there are no frontend tests

**Comment by chennisden** [comment]
(although I guess the real solution is to add frontend tests then)

**Comment by codekansas** [comment]
yea let's add some simple frontend test then instead rather than adding this flag

**Pull request closed without merging**
