### PR TITLE
Minor fixes for wasm

### PR DESCRIPTION
**Pull request by WT-MM**
**What does this PR do?**

Fixes some issues with the mujoco viewer by adding the actual wasm and three.js files

**What issues does this PR fix or reference?**

fixes #418

### CODE REVIEW

**Review by Winston-Hsiao — CHANGES_REQUESTED** [review]
omit node_modules? don't commit those changes. ensure that the package is installed (check `package.lock` and `package-lock.json`) and make sure required three js package and other dependences are there.

**Comment by codekansas** [comment]
why not host mujoco wasm on https://www.jsdelivr.com/ ?

**Comment by WT-MM** [comment]
It's using [this](https://github.com/zalo/mujoco_wasm) fork of mujoco-wasm which I don't think is on npm but yeah would probably be simpler to use jsdelivr

**Comment by codekansas** [comment]
let's put on jsdelivr then - made an issue for it #427

**Comment by Winston-Hsiao** [comment]
@codekansas @WT-MM yeah looks like jsdelivr can also serve from a GitHub repo. Main concern is relying on 3rd party, our MuJoCo WASM viewer will have downtime if jsdelivr has any outages and if that repo becomes private or something.

I think for the time being this will work but we should look into some better long term solution.

Honestly the more I look at it, maybe we do just pull in all the MuJoCo WASM code, and I think we can just do a standard install of [Three.js since that's a very popular node package](https://www.npmjs.com/package/three).

I'll work on this tomorrow, but the approach I'm thinking of taking is merging the MuJoCo code and doing normal import of three.js

**Review by Winston-Hsiao — APPROVED** [review]

**Comment by codekansas** [comment]
@Winston-Hsiao @WT-MM request - rather than putting this into the main repo, let's just host it on our own cdn (or jsdelivr). the issue is that now the git repo is really large and it slow down many other steps (cloning repo, deploying to prod, etc)

**Pull request merged**
